[package]
name = "merkle"
version = "0.1.0"
edition = "2021"
author = "Nate Cable"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha256 = "^1.4.0"
